// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package wsshards

import (
	"context"
	"encoding/json"
	"sync"
)

// Ensure, that clientMock does implement client.
// If this is not the case, regenerate this file with moq.
var _ client = &clientMock{}

// clientMock is a mock implementation of client.
//
//	func TestSomethingThatUsesclient(t *testing.T) {
//
//		// make and configure a mocked client
//		mockedclient := &clientMock{
//			CloseFunc: func()  {
//				panic("mock out the Close method")
//			},
//			OnReadFunc: func(fn func(context.Context, json.RawMessage))  {
//				panic("mock out the OnRead method")
//			},
//		}
//
//		// use mockedclient in code that requires client
//		// and then make assertions.
//
//	}
type clientMock struct {
	// CloseFunc mocks the Close method.
	CloseFunc func()

	// OnReadFunc mocks the OnRead method.
	OnReadFunc func(fn func(context.Context, json.RawMessage))

	// calls tracks calls to the methods.
	calls struct {
		// Close holds details about calls to the Close method.
		Close []struct {
		}
		// OnRead holds details about calls to the OnRead method.
		OnRead []struct {
			// Fn is the fn argument value.
			Fn func(context.Context, json.RawMessage)
		}
	}
	lockClose  sync.RWMutex
	lockOnRead sync.RWMutex
}

// Close calls CloseFunc.
func (mock *clientMock) Close() {
	callInfo := struct {
	}{}
	mock.lockClose.Lock()
	mock.calls.Close = append(mock.calls.Close, callInfo)
	mock.lockClose.Unlock()
	if mock.CloseFunc == nil {
		return
	}
	mock.CloseFunc()
}

// CloseCalls gets all the calls that were made to Close.
// Check the length with:
//
//	len(mockedclient.CloseCalls())
func (mock *clientMock) CloseCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockClose.RLock()
	calls = mock.calls.Close
	mock.lockClose.RUnlock()
	return calls
}

// OnRead calls OnReadFunc.
func (mock *clientMock) OnRead(fn func(context.Context, json.RawMessage)) {
	callInfo := struct {
		Fn func(context.Context, json.RawMessage)
	}{
		Fn: fn,
	}
	mock.lockOnRead.Lock()
	mock.calls.OnRead = append(mock.calls.OnRead, callInfo)
	mock.lockOnRead.Unlock()
	if mock.OnReadFunc == nil {
		return
	}
	mock.OnReadFunc(fn)
}

// OnReadCalls gets all the calls that were made to OnRead.
// Check the length with:
//
//	len(mockedclient.OnReadCalls())
func (mock *clientMock) OnReadCalls() []struct {
	Fn func(context.Context, json.RawMessage)
} {
	var calls []struct {
		Fn func(context.Context, json.RawMessage)
	}
	mock.lockOnRead.RLock()
	calls = mock.calls.OnRead
	mock.lockOnRead.RUnlock()
	return calls
}
