// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package wsshards

import (
	"context"
	"sync"
	"time"

	"github.com/davseby/wetsocks/wsclient/wsreconn"
)

// Ensure, that soloSubKeeperMock does implement soloSubKeeper.
// If this is not the case, regenerate this file with moq.
var _ soloSubKeeper = &soloSubKeeperMock{}

// soloSubKeeperMock is a mock implementation of soloSubKeeper.
//
//	func TestSomethingThatUsessoloSubKeeper(t *testing.T) {
//
//		// make and configure a mocked soloSubKeeper
//		mockedsoloSubKeeper := &soloSubKeeperMock{
//			CloseFunc: func()  {
//				panic("mock out the Close method")
//			},
//			ConfirmSubFunc: func(topic string)  {
//				panic("mock out the ConfirmSub method")
//			},
//			ConfirmUnsubFunc: func(topic string)  {
//				panic("mock out the ConfirmUnsub method")
//			},
//			OnChangeFunc: func(fn func(context.Context))  {
//				panic("mock out the OnChange method")
//			},
//			PayloadsFunc: func() ([]wsreconn.SubPayloader, time.Duration) {
//				panic("mock out the Payloads method")
//			},
//			ResetAllFunc: func()  {
//				panic("mock out the ResetAll method")
//			},
//			SubscribeFunc: func(topic string)  {
//				panic("mock out the Subscribe method")
//			},
//			UnsubscribeFunc: func(topic string)  {
//				panic("mock out the Unsubscribe method")
//			},
//			UnsubscribeAllFunc: func()  {
//				panic("mock out the UnsubscribeAll method")
//			},
//			UnsubscribeLocalFunc: func(topic string)  {
//				panic("mock out the UnsubscribeLocal method")
//			},
//		}
//
//		// use mockedsoloSubKeeper in code that requires soloSubKeeper
//		// and then make assertions.
//
//	}
type soloSubKeeperMock struct {
	// CloseFunc mocks the Close method.
	CloseFunc func()

	// ConfirmSubFunc mocks the ConfirmSub method.
	ConfirmSubFunc func(topic string)

	// ConfirmUnsubFunc mocks the ConfirmUnsub method.
	ConfirmUnsubFunc func(topic string)

	// OnChangeFunc mocks the OnChange method.
	OnChangeFunc func(fn func(context.Context))

	// PayloadsFunc mocks the Payloads method.
	PayloadsFunc func() ([]wsreconn.SubPayloader, time.Duration)

	// ResetAllFunc mocks the ResetAll method.
	ResetAllFunc func()

	// SubscribeFunc mocks the Subscribe method.
	SubscribeFunc func(topic string)

	// UnsubscribeFunc mocks the Unsubscribe method.
	UnsubscribeFunc func(topic string)

	// UnsubscribeAllFunc mocks the UnsubscribeAll method.
	UnsubscribeAllFunc func()

	// UnsubscribeLocalFunc mocks the UnsubscribeLocal method.
	UnsubscribeLocalFunc func(topic string)

	// calls tracks calls to the methods.
	calls struct {
		// Close holds details about calls to the Close method.
		Close []struct {
		}
		// ConfirmSub holds details about calls to the ConfirmSub method.
		ConfirmSub []struct {
			// Topic is the topic argument value.
			Topic string
		}
		// ConfirmUnsub holds details about calls to the ConfirmUnsub method.
		ConfirmUnsub []struct {
			// Topic is the topic argument value.
			Topic string
		}
		// OnChange holds details about calls to the OnChange method.
		OnChange []struct {
			// Fn is the fn argument value.
			Fn func(context.Context)
		}
		// Payloads holds details about calls to the Payloads method.
		Payloads []struct {
		}
		// ResetAll holds details about calls to the ResetAll method.
		ResetAll []struct {
		}
		// Subscribe holds details about calls to the Subscribe method.
		Subscribe []struct {
			// Topic is the topic argument value.
			Topic string
		}
		// Unsubscribe holds details about calls to the Unsubscribe method.
		Unsubscribe []struct {
			// Topic is the topic argument value.
			Topic string
		}
		// UnsubscribeAll holds details about calls to the UnsubscribeAll method.
		UnsubscribeAll []struct {
		}
		// UnsubscribeLocal holds details about calls to the UnsubscribeLocal method.
		UnsubscribeLocal []struct {
			// Topic is the topic argument value.
			Topic string
		}
	}
	lockClose            sync.RWMutex
	lockConfirmSub       sync.RWMutex
	lockConfirmUnsub     sync.RWMutex
	lockOnChange         sync.RWMutex
	lockPayloads         sync.RWMutex
	lockResetAll         sync.RWMutex
	lockSubscribe        sync.RWMutex
	lockUnsubscribe      sync.RWMutex
	lockUnsubscribeAll   sync.RWMutex
	lockUnsubscribeLocal sync.RWMutex
}

// Close calls CloseFunc.
func (mock *soloSubKeeperMock) Close() {
	callInfo := struct {
	}{}
	mock.lockClose.Lock()
	mock.calls.Close = append(mock.calls.Close, callInfo)
	mock.lockClose.Unlock()
	if mock.CloseFunc == nil {
		return
	}
	mock.CloseFunc()
}

// CloseCalls gets all the calls that were made to Close.
// Check the length with:
//
//	len(mockedsoloSubKeeper.CloseCalls())
func (mock *soloSubKeeperMock) CloseCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockClose.RLock()
	calls = mock.calls.Close
	mock.lockClose.RUnlock()
	return calls
}

// ConfirmSub calls ConfirmSubFunc.
func (mock *soloSubKeeperMock) ConfirmSub(topic string) {
	callInfo := struct {
		Topic string
	}{
		Topic: topic,
	}
	mock.lockConfirmSub.Lock()
	mock.calls.ConfirmSub = append(mock.calls.ConfirmSub, callInfo)
	mock.lockConfirmSub.Unlock()
	if mock.ConfirmSubFunc == nil {
		return
	}
	mock.ConfirmSubFunc(topic)
}

// ConfirmSubCalls gets all the calls that were made to ConfirmSub.
// Check the length with:
//
//	len(mockedsoloSubKeeper.ConfirmSubCalls())
func (mock *soloSubKeeperMock) ConfirmSubCalls() []struct {
	Topic string
} {
	var calls []struct {
		Topic string
	}
	mock.lockConfirmSub.RLock()
	calls = mock.calls.ConfirmSub
	mock.lockConfirmSub.RUnlock()
	return calls
}

// ConfirmUnsub calls ConfirmUnsubFunc.
func (mock *soloSubKeeperMock) ConfirmUnsub(topic string) {
	callInfo := struct {
		Topic string
	}{
		Topic: topic,
	}
	mock.lockConfirmUnsub.Lock()
	mock.calls.ConfirmUnsub = append(mock.calls.ConfirmUnsub, callInfo)
	mock.lockConfirmUnsub.Unlock()
	if mock.ConfirmUnsubFunc == nil {
		return
	}
	mock.ConfirmUnsubFunc(topic)
}

// ConfirmUnsubCalls gets all the calls that were made to ConfirmUnsub.
// Check the length with:
//
//	len(mockedsoloSubKeeper.ConfirmUnsubCalls())
func (mock *soloSubKeeperMock) ConfirmUnsubCalls() []struct {
	Topic string
} {
	var calls []struct {
		Topic string
	}
	mock.lockConfirmUnsub.RLock()
	calls = mock.calls.ConfirmUnsub
	mock.lockConfirmUnsub.RUnlock()
	return calls
}

// OnChange calls OnChangeFunc.
func (mock *soloSubKeeperMock) OnChange(fn func(context.Context)) {
	callInfo := struct {
		Fn func(context.Context)
	}{
		Fn: fn,
	}
	mock.lockOnChange.Lock()
	mock.calls.OnChange = append(mock.calls.OnChange, callInfo)
	mock.lockOnChange.Unlock()
	if mock.OnChangeFunc == nil {
		return
	}
	mock.OnChangeFunc(fn)
}

// OnChangeCalls gets all the calls that were made to OnChange.
// Check the length with:
//
//	len(mockedsoloSubKeeper.OnChangeCalls())
func (mock *soloSubKeeperMock) OnChangeCalls() []struct {
	Fn func(context.Context)
} {
	var calls []struct {
		Fn func(context.Context)
	}
	mock.lockOnChange.RLock()
	calls = mock.calls.OnChange
	mock.lockOnChange.RUnlock()
	return calls
}

// Payloads calls PayloadsFunc.
func (mock *soloSubKeeperMock) Payloads() ([]wsreconn.SubPayloader, time.Duration) {
	callInfo := struct {
	}{}
	mock.lockPayloads.Lock()
	mock.calls.Payloads = append(mock.calls.Payloads, callInfo)
	mock.lockPayloads.Unlock()
	if mock.PayloadsFunc == nil {
		var (
			subPayloadersOut []wsreconn.SubPayloader
			durationOut      time.Duration
		)
		return subPayloadersOut, durationOut
	}
	return mock.PayloadsFunc()
}

// PayloadsCalls gets all the calls that were made to Payloads.
// Check the length with:
//
//	len(mockedsoloSubKeeper.PayloadsCalls())
func (mock *soloSubKeeperMock) PayloadsCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockPayloads.RLock()
	calls = mock.calls.Payloads
	mock.lockPayloads.RUnlock()
	return calls
}

// ResetAll calls ResetAllFunc.
func (mock *soloSubKeeperMock) ResetAll() {
	callInfo := struct {
	}{}
	mock.lockResetAll.Lock()
	mock.calls.ResetAll = append(mock.calls.ResetAll, callInfo)
	mock.lockResetAll.Unlock()
	if mock.ResetAllFunc == nil {
		return
	}
	mock.ResetAllFunc()
}

// ResetAllCalls gets all the calls that were made to ResetAll.
// Check the length with:
//
//	len(mockedsoloSubKeeper.ResetAllCalls())
func (mock *soloSubKeeperMock) ResetAllCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockResetAll.RLock()
	calls = mock.calls.ResetAll
	mock.lockResetAll.RUnlock()
	return calls
}

// Subscribe calls SubscribeFunc.
func (mock *soloSubKeeperMock) Subscribe(topic string) {
	callInfo := struct {
		Topic string
	}{
		Topic: topic,
	}
	mock.lockSubscribe.Lock()
	mock.calls.Subscribe = append(mock.calls.Subscribe, callInfo)
	mock.lockSubscribe.Unlock()
	if mock.SubscribeFunc == nil {
		return
	}
	mock.SubscribeFunc(topic)
}

// SubscribeCalls gets all the calls that were made to Subscribe.
// Check the length with:
//
//	len(mockedsoloSubKeeper.SubscribeCalls())
func (mock *soloSubKeeperMock) SubscribeCalls() []struct {
	Topic string
} {
	var calls []struct {
		Topic string
	}
	mock.lockSubscribe.RLock()
	calls = mock.calls.Subscribe
	mock.lockSubscribe.RUnlock()
	return calls
}

// Unsubscribe calls UnsubscribeFunc.
func (mock *soloSubKeeperMock) Unsubscribe(topic string) {
	callInfo := struct {
		Topic string
	}{
		Topic: topic,
	}
	mock.lockUnsubscribe.Lock()
	mock.calls.Unsubscribe = append(mock.calls.Unsubscribe, callInfo)
	mock.lockUnsubscribe.Unlock()
	if mock.UnsubscribeFunc == nil {
		return
	}
	mock.UnsubscribeFunc(topic)
}

// UnsubscribeCalls gets all the calls that were made to Unsubscribe.
// Check the length with:
//
//	len(mockedsoloSubKeeper.UnsubscribeCalls())
func (mock *soloSubKeeperMock) UnsubscribeCalls() []struct {
	Topic string
} {
	var calls []struct {
		Topic string
	}
	mock.lockUnsubscribe.RLock()
	calls = mock.calls.Unsubscribe
	mock.lockUnsubscribe.RUnlock()
	return calls
}

// UnsubscribeAll calls UnsubscribeAllFunc.
func (mock *soloSubKeeperMock) UnsubscribeAll() {
	callInfo := struct {
	}{}
	mock.lockUnsubscribeAll.Lock()
	mock.calls.UnsubscribeAll = append(mock.calls.UnsubscribeAll, callInfo)
	mock.lockUnsubscribeAll.Unlock()
	if mock.UnsubscribeAllFunc == nil {
		return
	}
	mock.UnsubscribeAllFunc()
}

// UnsubscribeAllCalls gets all the calls that were made to UnsubscribeAll.
// Check the length with:
//
//	len(mockedsoloSubKeeper.UnsubscribeAllCalls())
func (mock *soloSubKeeperMock) UnsubscribeAllCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockUnsubscribeAll.RLock()
	calls = mock.calls.UnsubscribeAll
	mock.lockUnsubscribeAll.RUnlock()
	return calls
}

// UnsubscribeLocal calls UnsubscribeLocalFunc.
func (mock *soloSubKeeperMock) UnsubscribeLocal(topic string) {
	callInfo := struct {
		Topic string
	}{
		Topic: topic,
	}
	mock.lockUnsubscribeLocal.Lock()
	mock.calls.UnsubscribeLocal = append(mock.calls.UnsubscribeLocal, callInfo)
	mock.lockUnsubscribeLocal.Unlock()
	if mock.UnsubscribeLocalFunc == nil {
		return
	}
	mock.UnsubscribeLocalFunc(topic)
}

// UnsubscribeLocalCalls gets all the calls that were made to UnsubscribeLocal.
// Check the length with:
//
//	len(mockedsoloSubKeeper.UnsubscribeLocalCalls())
func (mock *soloSubKeeperMock) UnsubscribeLocalCalls() []struct {
	Topic string
} {
	var calls []struct {
		Topic string
	}
	mock.lockUnsubscribeLocal.RLock()
	calls = mock.calls.UnsubscribeLocal
	mock.lockUnsubscribeLocal.RUnlock()
	return calls
}
