// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package wsshards

import (
	"context"
	"sync"
	"time"

	"github.com/davseby/wetsocks/wsclient/wsreconn"
)

// Ensure, that groupedSubKeeperMock does implement groupedSubKeeper.
// If this is not the case, regenerate this file with moq.
var _ groupedSubKeeper[any] = &groupedSubKeeperMock[any]{}

// groupedSubKeeperMock is a mock implementation of groupedSubKeeper.
//
//	func TestSomethingThatUsesgroupedSubKeeper(t *testing.T) {
//
//		// make and configure a mocked groupedSubKeeper
//		mockedgroupedSubKeeper := &groupedSubKeeperMock{
//			CloseFunc: func()  {
//				panic("mock out the Close method")
//			},
//			ConfirmSubFunc: func(topic string, keys ...K)  {
//				panic("mock out the ConfirmSub method")
//			},
//			ConfirmUnsubFunc: func(topic string, invert bool, keys ...K)  {
//				panic("mock out the ConfirmUnsub method")
//			},
//			OnChangeFunc: func(fn func(context.Context))  {
//				panic("mock out the OnChange method")
//			},
//			PayloadsFunc: func() ([]wsreconn.SubPayloader, time.Duration) {
//				panic("mock out the Payloads method")
//			},
//			ResetAllFunc: func()  {
//				panic("mock out the ResetAll method")
//			},
//			SubscribeFunc: func(topic string, keys ...K)  {
//				panic("mock out the Subscribe method")
//			},
//			UnsubscribeFunc: func(topic string, keys ...K)  {
//				panic("mock out the Unsubscribe method")
//			},
//			UnsubscribeAllFunc: func()  {
//				panic("mock out the UnsubscribeAll method")
//			},
//		}
//
//		// use mockedgroupedSubKeeper in code that requires groupedSubKeeper
//		// and then make assertions.
//
//	}
type groupedSubKeeperMock[K comparable] struct {
	// CloseFunc mocks the Close method.
	CloseFunc func()

	// ConfirmSubFunc mocks the ConfirmSub method.
	ConfirmSubFunc func(topic string, keys ...K)

	// ConfirmUnsubFunc mocks the ConfirmUnsub method.
	ConfirmUnsubFunc func(topic string, invert bool, keys ...K)

	// OnChangeFunc mocks the OnChange method.
	OnChangeFunc func(fn func(context.Context))

	// PayloadsFunc mocks the Payloads method.
	PayloadsFunc func() ([]wsreconn.SubPayloader, time.Duration)

	// ResetAllFunc mocks the ResetAll method.
	ResetAllFunc func()

	// SubscribeFunc mocks the Subscribe method.
	SubscribeFunc func(topic string, keys ...K)

	// UnsubscribeFunc mocks the Unsubscribe method.
	UnsubscribeFunc func(topic string, keys ...K)

	// UnsubscribeAllFunc mocks the UnsubscribeAll method.
	UnsubscribeAllFunc func()

	// calls tracks calls to the methods.
	calls struct {
		// Close holds details about calls to the Close method.
		Close []struct {
		}
		// ConfirmSub holds details about calls to the ConfirmSub method.
		ConfirmSub []struct {
			// Topic is the topic argument value.
			Topic string
			// Keys is the keys argument value.
			Keys []K
		}
		// ConfirmUnsub holds details about calls to the ConfirmUnsub method.
		ConfirmUnsub []struct {
			// Topic is the topic argument value.
			Topic string
			// Invert is the invert argument value.
			Invert bool
			// Keys is the keys argument value.
			Keys []K
		}
		// OnChange holds details about calls to the OnChange method.
		OnChange []struct {
			// Fn is the fn argument value.
			Fn func(context.Context)
		}
		// Payloads holds details about calls to the Payloads method.
		Payloads []struct {
		}
		// ResetAll holds details about calls to the ResetAll method.
		ResetAll []struct {
		}
		// Subscribe holds details about calls to the Subscribe method.
		Subscribe []struct {
			// Topic is the topic argument value.
			Topic string
			// Keys is the keys argument value.
			Keys []K
		}
		// Unsubscribe holds details about calls to the Unsubscribe method.
		Unsubscribe []struct {
			// Topic is the topic argument value.
			Topic string
			// Keys is the keys argument value.
			Keys []K
		}
		// UnsubscribeAll holds details about calls to the UnsubscribeAll method.
		UnsubscribeAll []struct {
		}
	}
	lockClose          sync.RWMutex
	lockConfirmSub     sync.RWMutex
	lockConfirmUnsub   sync.RWMutex
	lockOnChange       sync.RWMutex
	lockPayloads       sync.RWMutex
	lockResetAll       sync.RWMutex
	lockSubscribe      sync.RWMutex
	lockUnsubscribe    sync.RWMutex
	lockUnsubscribeAll sync.RWMutex
}

// Close calls CloseFunc.
func (mock *groupedSubKeeperMock[K]) Close() {
	callInfo := struct {
	}{}
	mock.lockClose.Lock()
	mock.calls.Close = append(mock.calls.Close, callInfo)
	mock.lockClose.Unlock()
	if mock.CloseFunc == nil {
		return
	}
	mock.CloseFunc()
}

// CloseCalls gets all the calls that were made to Close.
// Check the length with:
//
//	len(mockedgroupedSubKeeper.CloseCalls())
func (mock *groupedSubKeeperMock[K]) CloseCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockClose.RLock()
	calls = mock.calls.Close
	mock.lockClose.RUnlock()
	return calls
}

// ConfirmSub calls ConfirmSubFunc.
func (mock *groupedSubKeeperMock[K]) ConfirmSub(topic string, keys ...K) {
	callInfo := struct {
		Topic string
		Keys  []K
	}{
		Topic: topic,
		Keys:  keys,
	}
	mock.lockConfirmSub.Lock()
	mock.calls.ConfirmSub = append(mock.calls.ConfirmSub, callInfo)
	mock.lockConfirmSub.Unlock()
	if mock.ConfirmSubFunc == nil {
		return
	}
	mock.ConfirmSubFunc(topic, keys...)
}

// ConfirmSubCalls gets all the calls that were made to ConfirmSub.
// Check the length with:
//
//	len(mockedgroupedSubKeeper.ConfirmSubCalls())
func (mock *groupedSubKeeperMock[K]) ConfirmSubCalls() []struct {
	Topic string
	Keys  []K
} {
	var calls []struct {
		Topic string
		Keys  []K
	}
	mock.lockConfirmSub.RLock()
	calls = mock.calls.ConfirmSub
	mock.lockConfirmSub.RUnlock()
	return calls
}

// ConfirmUnsub calls ConfirmUnsubFunc.
func (mock *groupedSubKeeperMock[K]) ConfirmUnsub(topic string, invert bool, keys ...K) {
	callInfo := struct {
		Topic  string
		Invert bool
		Keys   []K
	}{
		Topic:  topic,
		Invert: invert,
		Keys:   keys,
	}
	mock.lockConfirmUnsub.Lock()
	mock.calls.ConfirmUnsub = append(mock.calls.ConfirmUnsub, callInfo)
	mock.lockConfirmUnsub.Unlock()
	if mock.ConfirmUnsubFunc == nil {
		return
	}
	mock.ConfirmUnsubFunc(topic, invert, keys...)
}

// ConfirmUnsubCalls gets all the calls that were made to ConfirmUnsub.
// Check the length with:
//
//	len(mockedgroupedSubKeeper.ConfirmUnsubCalls())
func (mock *groupedSubKeeperMock[K]) ConfirmUnsubCalls() []struct {
	Topic  string
	Invert bool
	Keys   []K
} {
	var calls []struct {
		Topic  string
		Invert bool
		Keys   []K
	}
	mock.lockConfirmUnsub.RLock()
	calls = mock.calls.ConfirmUnsub
	mock.lockConfirmUnsub.RUnlock()
	return calls
}

// OnChange calls OnChangeFunc.
func (mock *groupedSubKeeperMock[K]) OnChange(fn func(context.Context)) {
	callInfo := struct {
		Fn func(context.Context)
	}{
		Fn: fn,
	}
	mock.lockOnChange.Lock()
	mock.calls.OnChange = append(mock.calls.OnChange, callInfo)
	mock.lockOnChange.Unlock()
	if mock.OnChangeFunc == nil {
		return
	}
	mock.OnChangeFunc(fn)
}

// OnChangeCalls gets all the calls that were made to OnChange.
// Check the length with:
//
//	len(mockedgroupedSubKeeper.OnChangeCalls())
func (mock *groupedSubKeeperMock[K]) OnChangeCalls() []struct {
	Fn func(context.Context)
} {
	var calls []struct {
		Fn func(context.Context)
	}
	mock.lockOnChange.RLock()
	calls = mock.calls.OnChange
	mock.lockOnChange.RUnlock()
	return calls
}

// Payloads calls PayloadsFunc.
func (mock *groupedSubKeeperMock[K]) Payloads() ([]wsreconn.SubPayloader, time.Duration) {
	callInfo := struct {
	}{}
	mock.lockPayloads.Lock()
	mock.calls.Payloads = append(mock.calls.Payloads, callInfo)
	mock.lockPayloads.Unlock()
	if mock.PayloadsFunc == nil {
		var (
			subPayloadersOut []wsreconn.SubPayloader
			durationOut      time.Duration
		)
		return subPayloadersOut, durationOut
	}
	return mock.PayloadsFunc()
}

// PayloadsCalls gets all the calls that were made to Payloads.
// Check the length with:
//
//	len(mockedgroupedSubKeeper.PayloadsCalls())
func (mock *groupedSubKeeperMock[K]) PayloadsCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockPayloads.RLock()
	calls = mock.calls.Payloads
	mock.lockPayloads.RUnlock()
	return calls
}

// ResetAll calls ResetAllFunc.
func (mock *groupedSubKeeperMock[K]) ResetAll() {
	callInfo := struct {
	}{}
	mock.lockResetAll.Lock()
	mock.calls.ResetAll = append(mock.calls.ResetAll, callInfo)
	mock.lockResetAll.Unlock()
	if mock.ResetAllFunc == nil {
		return
	}
	mock.ResetAllFunc()
}

// ResetAllCalls gets all the calls that were made to ResetAll.
// Check the length with:
//
//	len(mockedgroupedSubKeeper.ResetAllCalls())
func (mock *groupedSubKeeperMock[K]) ResetAllCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockResetAll.RLock()
	calls = mock.calls.ResetAll
	mock.lockResetAll.RUnlock()
	return calls
}

// Subscribe calls SubscribeFunc.
func (mock *groupedSubKeeperMock[K]) Subscribe(topic string, keys ...K) {
	callInfo := struct {
		Topic string
		Keys  []K
	}{
		Topic: topic,
		Keys:  keys,
	}
	mock.lockSubscribe.Lock()
	mock.calls.Subscribe = append(mock.calls.Subscribe, callInfo)
	mock.lockSubscribe.Unlock()
	if mock.SubscribeFunc == nil {
		return
	}
	mock.SubscribeFunc(topic, keys...)
}

// SubscribeCalls gets all the calls that were made to Subscribe.
// Check the length with:
//
//	len(mockedgroupedSubKeeper.SubscribeCalls())
func (mock *groupedSubKeeperMock[K]) SubscribeCalls() []struct {
	Topic string
	Keys  []K
} {
	var calls []struct {
		Topic string
		Keys  []K
	}
	mock.lockSubscribe.RLock()
	calls = mock.calls.Subscribe
	mock.lockSubscribe.RUnlock()
	return calls
}

// Unsubscribe calls UnsubscribeFunc.
func (mock *groupedSubKeeperMock[K]) Unsubscribe(topic string, keys ...K) {
	callInfo := struct {
		Topic string
		Keys  []K
	}{
		Topic: topic,
		Keys:  keys,
	}
	mock.lockUnsubscribe.Lock()
	mock.calls.Unsubscribe = append(mock.calls.Unsubscribe, callInfo)
	mock.lockUnsubscribe.Unlock()
	if mock.UnsubscribeFunc == nil {
		return
	}
	mock.UnsubscribeFunc(topic, keys...)
}

// UnsubscribeCalls gets all the calls that were made to Unsubscribe.
// Check the length with:
//
//	len(mockedgroupedSubKeeper.UnsubscribeCalls())
func (mock *groupedSubKeeperMock[K]) UnsubscribeCalls() []struct {
	Topic string
	Keys  []K
} {
	var calls []struct {
		Topic string
		Keys  []K
	}
	mock.lockUnsubscribe.RLock()
	calls = mock.calls.Unsubscribe
	mock.lockUnsubscribe.RUnlock()
	return calls
}

// UnsubscribeAll calls UnsubscribeAllFunc.
func (mock *groupedSubKeeperMock[K]) UnsubscribeAll() {
	callInfo := struct {
	}{}
	mock.lockUnsubscribeAll.Lock()
	mock.calls.UnsubscribeAll = append(mock.calls.UnsubscribeAll, callInfo)
	mock.lockUnsubscribeAll.Unlock()
	if mock.UnsubscribeAllFunc == nil {
		return
	}
	mock.UnsubscribeAllFunc()
}

// UnsubscribeAllCalls gets all the calls that were made to UnsubscribeAll.
// Check the length with:
//
//	len(mockedgroupedSubKeeper.UnsubscribeAllCalls())
func (mock *groupedSubKeeperMock[K]) UnsubscribeAllCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockUnsubscribeAll.RLock()
	calls = mock.calls.UnsubscribeAll
	mock.lockUnsubscribeAll.RUnlock()
	return calls
}
