// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package wsshards

import (
	"sync"

	"github.com/jellydator/wetsocks/wsclient/wsreconn"
)

// Ensure, that SubKeeperStoreMock does implement SubKeeperStore.
// If this is not the case, regenerate this file with moq.
var _ SubKeeperStore = &SubKeeperStoreMock{}

// SubKeeperStoreMock is a mock implementation of SubKeeperStore.
//
//	func TestSomethingThatUsesSubKeeperStore(t *testing.T) {
//
//		// make and configure a mocked SubKeeperStore
//		mockedSubKeeperStore := &SubKeeperStoreMock{
//			SubKeepersFunc: func() []wsreconn.SubKeeper {
//				panic("mock out the SubKeepers method")
//			},
//		}
//
//		// use mockedSubKeeperStore in code that requires SubKeeperStore
//		// and then make assertions.
//
//	}
type SubKeeperStoreMock struct {
	// SubKeepersFunc mocks the SubKeepers method.
	SubKeepersFunc func() []wsreconn.SubKeeper

	// calls tracks calls to the methods.
	calls struct {
		// SubKeepers holds details about calls to the SubKeepers method.
		SubKeepers []struct {
		}
	}
	lockSubKeepers sync.RWMutex
}

// SubKeepers calls SubKeepersFunc.
func (mock *SubKeeperStoreMock) SubKeepers() []wsreconn.SubKeeper {
	callInfo := struct {
	}{}
	mock.lockSubKeepers.Lock()
	mock.calls.SubKeepers = append(mock.calls.SubKeepers, callInfo)
	mock.lockSubKeepers.Unlock()
	if mock.SubKeepersFunc == nil {
		var (
			subKeepersOut []wsreconn.SubKeeper
		)
		return subKeepersOut
	}
	return mock.SubKeepersFunc()
}

// SubKeepersCalls gets all the calls that were made to SubKeepers.
// Check the length with:
//
//	len(mockedSubKeeperStore.SubKeepersCalls())
func (mock *SubKeeperStoreMock) SubKeepersCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockSubKeepers.RLock()
	calls = mock.calls.SubKeepers
	mock.lockSubKeepers.RUnlock()
	return calls
}
