version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    commit-message:
      prefix: "vendor"
      include: "scope"
    open-pull-requests-limit: 10
    groups:
      deps:
        update-types:
          - "minor"
          - "patch"
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    commit-message:
      prefix: "workflows"
      include: "scope"
    open-pull-requests-limit: 10
