// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"sync"

	"github.com/oxynote/wetsocks/wsclient/wsreconn"
)

// Ensure, that ClientMetrics does implement wsreconn.ClientMetrics.
// If this is not the case, regenerate this file with moq.
var _ wsreconn.ClientMetrics = &ClientMetrics{}

// ClientMetrics is a mock implementation of wsreconn.ClientMetrics.
//
//	func TestSomethingThatUsesClientMetrics(t *testing.T) {
//
//		// make and configure a mocked wsreconn.ClientMetrics
//		mockedClientMetrics := &ClientMetrics{
//			DecWsOpenConnectionsFunc: func()  {
//				panic("mock out the DecWsOpenConnections method")
//			},
//			IncWsConnectionAttemptsFunc: func()  {
//				panic("mock out the IncWsConnectionAttempts method")
//			},
//			IncWsOpenConnectionsFunc: func()  {
//				panic("mock out the IncWsOpenConnections method")
//			},
//			IncWsWritesFunc: func()  {
//				panic("mock out the IncWsWrites method")
//			},
//		}
//
//		// use mockedClientMetrics in code that requires wsreconn.ClientMetrics
//		// and then make assertions.
//
//	}
type ClientMetrics struct {
	// DecWsOpenConnectionsFunc mocks the DecWsOpenConnections method.
	DecWsOpenConnectionsFunc func()

	// IncWsConnectionAttemptsFunc mocks the IncWsConnectionAttempts method.
	IncWsConnectionAttemptsFunc func()

	// IncWsOpenConnectionsFunc mocks the IncWsOpenConnections method.
	IncWsOpenConnectionsFunc func()

	// IncWsWritesFunc mocks the IncWsWrites method.
	IncWsWritesFunc func()

	// calls tracks calls to the methods.
	calls struct {
		// DecWsOpenConnections holds details about calls to the DecWsOpenConnections method.
		DecWsOpenConnections []struct {
		}
		// IncWsConnectionAttempts holds details about calls to the IncWsConnectionAttempts method.
		IncWsConnectionAttempts []struct {
		}
		// IncWsOpenConnections holds details about calls to the IncWsOpenConnections method.
		IncWsOpenConnections []struct {
		}
		// IncWsWrites holds details about calls to the IncWsWrites method.
		IncWsWrites []struct {
		}
	}
	lockDecWsOpenConnections    sync.RWMutex
	lockIncWsConnectionAttempts sync.RWMutex
	lockIncWsOpenConnections    sync.RWMutex
	lockIncWsWrites             sync.RWMutex
}

// DecWsOpenConnections calls DecWsOpenConnectionsFunc.
func (mock *ClientMetrics) DecWsOpenConnections() {
	callInfo := struct {
	}{}
	mock.lockDecWsOpenConnections.Lock()
	mock.calls.DecWsOpenConnections = append(mock.calls.DecWsOpenConnections, callInfo)
	mock.lockDecWsOpenConnections.Unlock()
	if mock.DecWsOpenConnectionsFunc == nil {
		return
	}
	mock.DecWsOpenConnectionsFunc()
}

// DecWsOpenConnectionsCalls gets all the calls that were made to DecWsOpenConnections.
// Check the length with:
//
//	len(mockedClientMetrics.DecWsOpenConnectionsCalls())
func (mock *ClientMetrics) DecWsOpenConnectionsCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockDecWsOpenConnections.RLock()
	calls = mock.calls.DecWsOpenConnections
	mock.lockDecWsOpenConnections.RUnlock()
	return calls
}

// IncWsConnectionAttempts calls IncWsConnectionAttemptsFunc.
func (mock *ClientMetrics) IncWsConnectionAttempts() {
	callInfo := struct {
	}{}
	mock.lockIncWsConnectionAttempts.Lock()
	mock.calls.IncWsConnectionAttempts = append(mock.calls.IncWsConnectionAttempts, callInfo)
	mock.lockIncWsConnectionAttempts.Unlock()
	if mock.IncWsConnectionAttemptsFunc == nil {
		return
	}
	mock.IncWsConnectionAttemptsFunc()
}

// IncWsConnectionAttemptsCalls gets all the calls that were made to IncWsConnectionAttempts.
// Check the length with:
//
//	len(mockedClientMetrics.IncWsConnectionAttemptsCalls())
func (mock *ClientMetrics) IncWsConnectionAttemptsCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockIncWsConnectionAttempts.RLock()
	calls = mock.calls.IncWsConnectionAttempts
	mock.lockIncWsConnectionAttempts.RUnlock()
	return calls
}

// IncWsOpenConnections calls IncWsOpenConnectionsFunc.
func (mock *ClientMetrics) IncWsOpenConnections() {
	callInfo := struct {
	}{}
	mock.lockIncWsOpenConnections.Lock()
	mock.calls.IncWsOpenConnections = append(mock.calls.IncWsOpenConnections, callInfo)
	mock.lockIncWsOpenConnections.Unlock()
	if mock.IncWsOpenConnectionsFunc == nil {
		return
	}
	mock.IncWsOpenConnectionsFunc()
}

// IncWsOpenConnectionsCalls gets all the calls that were made to IncWsOpenConnections.
// Check the length with:
//
//	len(mockedClientMetrics.IncWsOpenConnectionsCalls())
func (mock *ClientMetrics) IncWsOpenConnectionsCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockIncWsOpenConnections.RLock()
	calls = mock.calls.IncWsOpenConnections
	mock.lockIncWsOpenConnections.RUnlock()
	return calls
}

// IncWsWrites calls IncWsWritesFunc.
func (mock *ClientMetrics) IncWsWrites() {
	callInfo := struct {
	}{}
	mock.lockIncWsWrites.Lock()
	mock.calls.IncWsWrites = append(mock.calls.IncWsWrites, callInfo)
	mock.lockIncWsWrites.Unlock()
	if mock.IncWsWritesFunc == nil {
		return
	}
	mock.IncWsWritesFunc()
}

// IncWsWritesCalls gets all the calls that were made to IncWsWrites.
// Check the length with:
//
//	len(mockedClientMetrics.IncWsWritesCalls())
func (mock *ClientMetrics) IncWsWritesCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockIncWsWrites.RLock()
	calls = mock.calls.IncWsWrites
	mock.lockIncWsWrites.RUnlock()
	return calls
}
