// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"sync"
	"time"

	"github.com/lucidence/wetsocks/wsclient/wsreconn"
)

// Ensure, that SubKeeper does implement wsreconn.SubKeeper.
// If this is not the case, regenerate this file with moq.
var _ wsreconn.SubKeeper = &SubKeeper{}

// SubKeeper is a mock implementation of wsreconn.SubKeeper.
//
//	func TestSomethingThatUsesSubKeeper(t *testing.T) {
//
//		// make and configure a mocked wsreconn.SubKeeper
//		mockedSubKeeper := &SubKeeper{
//			OnChangeFunc: func(fn func(context.Context))  {
//				panic("mock out the OnChange method")
//			},
//			PayloadsFunc: func() ([]wsreconn.SubPayloader, time.Duration) {
//				panic("mock out the Payloads method")
//			},
//			ResetAllFunc: func()  {
//				panic("mock out the ResetAll method")
//			},
//		}
//
//		// use mockedSubKeeper in code that requires wsreconn.SubKeeper
//		// and then make assertions.
//
//	}
type SubKeeper struct {
	// OnChangeFunc mocks the OnChange method.
	OnChangeFunc func(fn func(context.Context))

	// PayloadsFunc mocks the Payloads method.
	PayloadsFunc func() ([]wsreconn.SubPayloader, time.Duration)

	// ResetAllFunc mocks the ResetAll method.
	ResetAllFunc func()

	// calls tracks calls to the methods.
	calls struct {
		// OnChange holds details about calls to the OnChange method.
		OnChange []struct {
			// Fn is the fn argument value.
			Fn func(context.Context)
		}
		// Payloads holds details about calls to the Payloads method.
		Payloads []struct {
		}
		// ResetAll holds details about calls to the ResetAll method.
		ResetAll []struct {
		}
	}
	lockOnChange sync.RWMutex
	lockPayloads sync.RWMutex
	lockResetAll sync.RWMutex
}

// OnChange calls OnChangeFunc.
func (mock *SubKeeper) OnChange(fn func(context.Context)) {
	callInfo := struct {
		Fn func(context.Context)
	}{
		Fn: fn,
	}
	mock.lockOnChange.Lock()
	mock.calls.OnChange = append(mock.calls.OnChange, callInfo)
	mock.lockOnChange.Unlock()
	if mock.OnChangeFunc == nil {
		return
	}
	mock.OnChangeFunc(fn)
}

// OnChangeCalls gets all the calls that were made to OnChange.
// Check the length with:
//
//	len(mockedSubKeeper.OnChangeCalls())
func (mock *SubKeeper) OnChangeCalls() []struct {
	Fn func(context.Context)
} {
	var calls []struct {
		Fn func(context.Context)
	}
	mock.lockOnChange.RLock()
	calls = mock.calls.OnChange
	mock.lockOnChange.RUnlock()
	return calls
}

// Payloads calls PayloadsFunc.
func (mock *SubKeeper) Payloads() ([]wsreconn.SubPayloader, time.Duration) {
	callInfo := struct {
	}{}
	mock.lockPayloads.Lock()
	mock.calls.Payloads = append(mock.calls.Payloads, callInfo)
	mock.lockPayloads.Unlock()
	if mock.PayloadsFunc == nil {
		var (
			subPayloadersOut []wsreconn.SubPayloader
			durationOut      time.Duration
		)
		return subPayloadersOut, durationOut
	}
	return mock.PayloadsFunc()
}

// PayloadsCalls gets all the calls that were made to Payloads.
// Check the length with:
//
//	len(mockedSubKeeper.PayloadsCalls())
func (mock *SubKeeper) PayloadsCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockPayloads.RLock()
	calls = mock.calls.Payloads
	mock.lockPayloads.RUnlock()
	return calls
}

// ResetAll calls ResetAllFunc.
func (mock *SubKeeper) ResetAll() {
	callInfo := struct {
	}{}
	mock.lockResetAll.Lock()
	mock.calls.ResetAll = append(mock.calls.ResetAll, callInfo)
	mock.lockResetAll.Unlock()
	if mock.ResetAllFunc == nil {
		return
	}
	mock.ResetAllFunc()
}

// ResetAllCalls gets all the calls that were made to ResetAll.
// Check the length with:
//
//	len(mockedSubKeeper.ResetAllCalls())
func (mock *SubKeeper) ResetAllCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockResetAll.RLock()
	calls = mock.calls.ResetAll
	mock.lockResetAll.RUnlock()
	return calls
}
