// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"net/http"
	"sync"

	"github.com/davseby/wetsocks/wsserver"
)

// Ensure, that Pool does implement wsserver.Pool.
// If this is not the case, regenerate this file with moq.
var _ wsserver.Pool = &Pool{}

// Pool is a mock implementation of wsserver.Pool.
//
//	func TestSomethingThatUsesPool(t *testing.T) {
//
//		// make and configure a mocked wsserver.Pool
//		mockedPool := &Pool{
//			CloseFunc: func()  {
//				panic("mock out the Close method")
//			},
//			CloseConnFunc: func(filter func(context.Context) bool)  {
//				panic("mock out the CloseConn method")
//			},
//			ServeHTTPFunc: func(responseWriter http.ResponseWriter, request *http.Request)  {
//				panic("mock out the ServeHTTP method")
//			},
//		}
//
//		// use mockedPool in code that requires wsserver.Pool
//		// and then make assertions.
//
//	}
type Pool struct {
	// CloseFunc mocks the Close method.
	CloseFunc func()

	// CloseConnFunc mocks the CloseConn method.
	CloseConnFunc func(filter func(context.Context) bool)

	// ServeHTTPFunc mocks the ServeHTTP method.
	ServeHTTPFunc func(responseWriter http.ResponseWriter, request *http.Request)

	// calls tracks calls to the methods.
	calls struct {
		// Close holds details about calls to the Close method.
		Close []struct {
		}
		// CloseConn holds details about calls to the CloseConn method.
		CloseConn []struct {
			// Filter is the filter argument value.
			Filter func(context.Context) bool
		}
		// ServeHTTP holds details about calls to the ServeHTTP method.
		ServeHTTP []struct {
			// ResponseWriter is the responseWriter argument value.
			ResponseWriter http.ResponseWriter
			// Request is the request argument value.
			Request *http.Request
		}
	}
	lockClose     sync.RWMutex
	lockCloseConn sync.RWMutex
	lockServeHTTP sync.RWMutex
}

// Close calls CloseFunc.
func (mock *Pool) Close() {
	callInfo := struct {
	}{}
	mock.lockClose.Lock()
	mock.calls.Close = append(mock.calls.Close, callInfo)
	mock.lockClose.Unlock()
	if mock.CloseFunc == nil {
		return
	}
	mock.CloseFunc()
}

// CloseCalls gets all the calls that were made to Close.
// Check the length with:
//
//	len(mockedPool.CloseCalls())
func (mock *Pool) CloseCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockClose.RLock()
	calls = mock.calls.Close
	mock.lockClose.RUnlock()
	return calls
}

// CloseConn calls CloseConnFunc.
func (mock *Pool) CloseConn(filter func(context.Context) bool) {
	callInfo := struct {
		Filter func(context.Context) bool
	}{
		Filter: filter,
	}
	mock.lockCloseConn.Lock()
	mock.calls.CloseConn = append(mock.calls.CloseConn, callInfo)
	mock.lockCloseConn.Unlock()
	if mock.CloseConnFunc == nil {
		return
	}
	mock.CloseConnFunc(filter)
}

// CloseConnCalls gets all the calls that were made to CloseConn.
// Check the length with:
//
//	len(mockedPool.CloseConnCalls())
func (mock *Pool) CloseConnCalls() []struct {
	Filter func(context.Context) bool
} {
	var calls []struct {
		Filter func(context.Context) bool
	}
	mock.lockCloseConn.RLock()
	calls = mock.calls.CloseConn
	mock.lockCloseConn.RUnlock()
	return calls
}

// ServeHTTP calls ServeHTTPFunc.
func (mock *Pool) ServeHTTP(responseWriter http.ResponseWriter, request *http.Request) {
	callInfo := struct {
		ResponseWriter http.ResponseWriter
		Request        *http.Request
	}{
		ResponseWriter: responseWriter,
		Request:        request,
	}
	mock.lockServeHTTP.Lock()
	mock.calls.ServeHTTP = append(mock.calls.ServeHTTP, callInfo)
	mock.lockServeHTTP.Unlock()
	if mock.ServeHTTPFunc == nil {
		return
	}
	mock.ServeHTTPFunc(responseWriter, request)
}

// ServeHTTPCalls gets all the calls that were made to ServeHTTP.
// Check the length with:
//
//	len(mockedPool.ServeHTTPCalls())
func (mock *Pool) ServeHTTPCalls() []struct {
	ResponseWriter http.ResponseWriter
	Request        *http.Request
} {
	var calls []struct {
		ResponseWriter http.ResponseWriter
		Request        *http.Request
	}
	mock.lockServeHTTP.RLock()
	calls = mock.calls.ServeHTTP
	mock.lockServeHTTP.RUnlock()
	return calls
}
