// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"sync"

	"github.com/jellydator/wetsocks/wsserver"
)

// Ensure, that Topic does implement wsserver.Topic.
// If this is not the case, regenerate this file with moq.
var _ wsserver.Topic = &Topic{}

// Topic is a mock implementation of wsserver.Topic.
//
//	func TestSomethingThatUsesTopic(t *testing.T) {
//
//		// make and configure a mocked wsserver.Topic
//		mockedTopic := &Topic{
//			DropManyFunc: func(ctx context.Context, reason string, filter func(context.Context, string) bool)  {
//				panic("mock out the DropMany method")
//			},
//			DropOneFunc: func(ctx context.Context, reason string)  {
//				panic("mock out the DropOne method")
//			},
//			OnFirstSubFunc: func(fn func(context.Context))  {
//				panic("mock out the OnFirstSub method")
//			},
//			OnLastUnsubFunc: func(fn func(context.Context))  {
//				panic("mock out the OnLastUnsub method")
//			},
//			OnSubFunc: func(fn func(context.Context))  {
//				panic("mock out the OnSub method")
//			},
//			OnUnsubFunc: func(fn func(context.Context))  {
//				panic("mock out the OnUnsub method")
//			},
//			PublishFunc: func(ctx context.Context, payload any, filter func(context.Context, string) bool)  {
//				panic("mock out the Publish method")
//			},
//		}
//
//		// use mockedTopic in code that requires wsserver.Topic
//		// and then make assertions.
//
//	}
type Topic struct {
	// DropManyFunc mocks the DropMany method.
	DropManyFunc func(ctx context.Context, reason string, filter func(context.Context, string) bool)

	// DropOneFunc mocks the DropOne method.
	DropOneFunc func(ctx context.Context, reason string)

	// OnFirstSubFunc mocks the OnFirstSub method.
	OnFirstSubFunc func(fn func(context.Context))

	// OnLastUnsubFunc mocks the OnLastUnsub method.
	OnLastUnsubFunc func(fn func(context.Context))

	// OnSubFunc mocks the OnSub method.
	OnSubFunc func(fn func(context.Context))

	// OnUnsubFunc mocks the OnUnsub method.
	OnUnsubFunc func(fn func(context.Context))

	// PublishFunc mocks the Publish method.
	PublishFunc func(ctx context.Context, payload any, filter func(context.Context, string) bool)

	// calls tracks calls to the methods.
	calls struct {
		// DropMany holds details about calls to the DropMany method.
		DropMany []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Reason is the reason argument value.
			Reason string
			// Filter is the filter argument value.
			Filter func(context.Context, string) bool
		}
		// DropOne holds details about calls to the DropOne method.
		DropOne []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Reason is the reason argument value.
			Reason string
		}
		// OnFirstSub holds details about calls to the OnFirstSub method.
		OnFirstSub []struct {
			// Fn is the fn argument value.
			Fn func(context.Context)
		}
		// OnLastUnsub holds details about calls to the OnLastUnsub method.
		OnLastUnsub []struct {
			// Fn is the fn argument value.
			Fn func(context.Context)
		}
		// OnSub holds details about calls to the OnSub method.
		OnSub []struct {
			// Fn is the fn argument value.
			Fn func(context.Context)
		}
		// OnUnsub holds details about calls to the OnUnsub method.
		OnUnsub []struct {
			// Fn is the fn argument value.
			Fn func(context.Context)
		}
		// Publish holds details about calls to the Publish method.
		Publish []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Payload is the payload argument value.
			Payload any
			// Filter is the filter argument value.
			Filter func(context.Context, string) bool
		}
	}
	lockDropMany    sync.RWMutex
	lockDropOne     sync.RWMutex
	lockOnFirstSub  sync.RWMutex
	lockOnLastUnsub sync.RWMutex
	lockOnSub       sync.RWMutex
	lockOnUnsub     sync.RWMutex
	lockPublish     sync.RWMutex
}

// DropMany calls DropManyFunc.
func (mock *Topic) DropMany(ctx context.Context, reason string, filter func(context.Context, string) bool) {
	callInfo := struct {
		Ctx    context.Context
		Reason string
		Filter func(context.Context, string) bool
	}{
		Ctx:    ctx,
		Reason: reason,
		Filter: filter,
	}
	mock.lockDropMany.Lock()
	mock.calls.DropMany = append(mock.calls.DropMany, callInfo)
	mock.lockDropMany.Unlock()
	if mock.DropManyFunc == nil {
		return
	}
	mock.DropManyFunc(ctx, reason, filter)
}

// DropManyCalls gets all the calls that were made to DropMany.
// Check the length with:
//
//	len(mockedTopic.DropManyCalls())
func (mock *Topic) DropManyCalls() []struct {
	Ctx    context.Context
	Reason string
	Filter func(context.Context, string) bool
} {
	var calls []struct {
		Ctx    context.Context
		Reason string
		Filter func(context.Context, string) bool
	}
	mock.lockDropMany.RLock()
	calls = mock.calls.DropMany
	mock.lockDropMany.RUnlock()
	return calls
}

// DropOne calls DropOneFunc.
func (mock *Topic) DropOne(ctx context.Context, reason string) {
	callInfo := struct {
		Ctx    context.Context
		Reason string
	}{
		Ctx:    ctx,
		Reason: reason,
	}
	mock.lockDropOne.Lock()
	mock.calls.DropOne = append(mock.calls.DropOne, callInfo)
	mock.lockDropOne.Unlock()
	if mock.DropOneFunc == nil {
		return
	}
	mock.DropOneFunc(ctx, reason)
}

// DropOneCalls gets all the calls that were made to DropOne.
// Check the length with:
//
//	len(mockedTopic.DropOneCalls())
func (mock *Topic) DropOneCalls() []struct {
	Ctx    context.Context
	Reason string
} {
	var calls []struct {
		Ctx    context.Context
		Reason string
	}
	mock.lockDropOne.RLock()
	calls = mock.calls.DropOne
	mock.lockDropOne.RUnlock()
	return calls
}

// OnFirstSub calls OnFirstSubFunc.
func (mock *Topic) OnFirstSub(fn func(context.Context)) {
	callInfo := struct {
		Fn func(context.Context)
	}{
		Fn: fn,
	}
	mock.lockOnFirstSub.Lock()
	mock.calls.OnFirstSub = append(mock.calls.OnFirstSub, callInfo)
	mock.lockOnFirstSub.Unlock()
	if mock.OnFirstSubFunc == nil {
		return
	}
	mock.OnFirstSubFunc(fn)
}

// OnFirstSubCalls gets all the calls that were made to OnFirstSub.
// Check the length with:
//
//	len(mockedTopic.OnFirstSubCalls())
func (mock *Topic) OnFirstSubCalls() []struct {
	Fn func(context.Context)
} {
	var calls []struct {
		Fn func(context.Context)
	}
	mock.lockOnFirstSub.RLock()
	calls = mock.calls.OnFirstSub
	mock.lockOnFirstSub.RUnlock()
	return calls
}

// OnLastUnsub calls OnLastUnsubFunc.
func (mock *Topic) OnLastUnsub(fn func(context.Context)) {
	callInfo := struct {
		Fn func(context.Context)
	}{
		Fn: fn,
	}
	mock.lockOnLastUnsub.Lock()
	mock.calls.OnLastUnsub = append(mock.calls.OnLastUnsub, callInfo)
	mock.lockOnLastUnsub.Unlock()
	if mock.OnLastUnsubFunc == nil {
		return
	}
	mock.OnLastUnsubFunc(fn)
}

// OnLastUnsubCalls gets all the calls that were made to OnLastUnsub.
// Check the length with:
//
//	len(mockedTopic.OnLastUnsubCalls())
func (mock *Topic) OnLastUnsubCalls() []struct {
	Fn func(context.Context)
} {
	var calls []struct {
		Fn func(context.Context)
	}
	mock.lockOnLastUnsub.RLock()
	calls = mock.calls.OnLastUnsub
	mock.lockOnLastUnsub.RUnlock()
	return calls
}

// OnSub calls OnSubFunc.
func (mock *Topic) OnSub(fn func(context.Context)) {
	callInfo := struct {
		Fn func(context.Context)
	}{
		Fn: fn,
	}
	mock.lockOnSub.Lock()
	mock.calls.OnSub = append(mock.calls.OnSub, callInfo)
	mock.lockOnSub.Unlock()
	if mock.OnSubFunc == nil {
		return
	}
	mock.OnSubFunc(fn)
}

// OnSubCalls gets all the calls that were made to OnSub.
// Check the length with:
//
//	len(mockedTopic.OnSubCalls())
func (mock *Topic) OnSubCalls() []struct {
	Fn func(context.Context)
} {
	var calls []struct {
		Fn func(context.Context)
	}
	mock.lockOnSub.RLock()
	calls = mock.calls.OnSub
	mock.lockOnSub.RUnlock()
	return calls
}

// OnUnsub calls OnUnsubFunc.
func (mock *Topic) OnUnsub(fn func(context.Context)) {
	callInfo := struct {
		Fn func(context.Context)
	}{
		Fn: fn,
	}
	mock.lockOnUnsub.Lock()
	mock.calls.OnUnsub = append(mock.calls.OnUnsub, callInfo)
	mock.lockOnUnsub.Unlock()
	if mock.OnUnsubFunc == nil {
		return
	}
	mock.OnUnsubFunc(fn)
}

// OnUnsubCalls gets all the calls that were made to OnUnsub.
// Check the length with:
//
//	len(mockedTopic.OnUnsubCalls())
func (mock *Topic) OnUnsubCalls() []struct {
	Fn func(context.Context)
} {
	var calls []struct {
		Fn func(context.Context)
	}
	mock.lockOnUnsub.RLock()
	calls = mock.calls.OnUnsub
	mock.lockOnUnsub.RUnlock()
	return calls
}

// Publish calls PublishFunc.
func (mock *Topic) Publish(ctx context.Context, payload any, filter func(context.Context, string) bool) {
	callInfo := struct {
		Ctx     context.Context
		Payload any
		Filter  func(context.Context, string) bool
	}{
		Ctx:     ctx,
		Payload: payload,
		Filter:  filter,
	}
	mock.lockPublish.Lock()
	mock.calls.Publish = append(mock.calls.Publish, callInfo)
	mock.lockPublish.Unlock()
	if mock.PublishFunc == nil {
		return
	}
	mock.PublishFunc(ctx, payload, filter)
}

// PublishCalls gets all the calls that were made to Publish.
// Check the length with:
//
//	len(mockedTopic.PublishCalls())
func (mock *Topic) PublishCalls() []struct {
	Ctx     context.Context
	Payload any
	Filter  func(context.Context, string) bool
} {
	var calls []struct {
		Ctx     context.Context
		Payload any
		Filter  func(context.Context, string) bool
	}
	mock.lockPublish.RLock()
	calls = mock.calls.Publish
	mock.lockPublish.RUnlock()
	return calls
}
