// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package wsreconn

import (
	"sync"
)

// Ensure, that SubKeeperMetricsMock does implement SubKeeperMetrics.
// If this is not the case, regenerate this file with moq.
var _ SubKeeperMetrics = &SubKeeperMetricsMock{}

// SubKeeperMetricsMock is a mock implementation of SubKeeperMetrics.
//
//	func TestSomethingThatUsesSubKeeperMetrics(t *testing.T) {
//
//		// make and configure a mocked SubKeeperMetrics
//		mockedSubKeeperMetrics := &SubKeeperMetricsMock{
//			DecWsSubsFunc: func()  {
//				panic("mock out the DecWsSubs method")
//			},
//			IncWsSubConfirmationsFunc: func()  {
//				panic("mock out the IncWsSubConfirmations method")
//			},
//			IncWsSubsFunc: func()  {
//				panic("mock out the IncWsSubs method")
//			},
//			IncWsUnsubConfirmationsFunc: func()  {
//				panic("mock out the IncWsUnsubConfirmations method")
//			},
//		}
//
//		// use mockedSubKeeperMetrics in code that requires SubKeeperMetrics
//		// and then make assertions.
//
//	}
type SubKeeperMetricsMock struct {
	// DecWsSubsFunc mocks the DecWsSubs method.
	DecWsSubsFunc func()

	// IncWsSubConfirmationsFunc mocks the IncWsSubConfirmations method.
	IncWsSubConfirmationsFunc func()

	// IncWsSubsFunc mocks the IncWsSubs method.
	IncWsSubsFunc func()

	// IncWsUnsubConfirmationsFunc mocks the IncWsUnsubConfirmations method.
	IncWsUnsubConfirmationsFunc func()

	// calls tracks calls to the methods.
	calls struct {
		// DecWsSubs holds details about calls to the DecWsSubs method.
		DecWsSubs []struct {
		}
		// IncWsSubConfirmations holds details about calls to the IncWsSubConfirmations method.
		IncWsSubConfirmations []struct {
		}
		// IncWsSubs holds details about calls to the IncWsSubs method.
		IncWsSubs []struct {
		}
		// IncWsUnsubConfirmations holds details about calls to the IncWsUnsubConfirmations method.
		IncWsUnsubConfirmations []struct {
		}
	}
	lockDecWsSubs               sync.RWMutex
	lockIncWsSubConfirmations   sync.RWMutex
	lockIncWsSubs               sync.RWMutex
	lockIncWsUnsubConfirmations sync.RWMutex
}

// DecWsSubs calls DecWsSubsFunc.
func (mock *SubKeeperMetricsMock) DecWsSubs() {
	callInfo := struct {
	}{}
	mock.lockDecWsSubs.Lock()
	mock.calls.DecWsSubs = append(mock.calls.DecWsSubs, callInfo)
	mock.lockDecWsSubs.Unlock()
	if mock.DecWsSubsFunc == nil {
		return
	}
	mock.DecWsSubsFunc()
}

// DecWsSubsCalls gets all the calls that were made to DecWsSubs.
// Check the length with:
//
//	len(mockedSubKeeperMetrics.DecWsSubsCalls())
func (mock *SubKeeperMetricsMock) DecWsSubsCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockDecWsSubs.RLock()
	calls = mock.calls.DecWsSubs
	mock.lockDecWsSubs.RUnlock()
	return calls
}

// IncWsSubConfirmations calls IncWsSubConfirmationsFunc.
func (mock *SubKeeperMetricsMock) IncWsSubConfirmations() {
	callInfo := struct {
	}{}
	mock.lockIncWsSubConfirmations.Lock()
	mock.calls.IncWsSubConfirmations = append(mock.calls.IncWsSubConfirmations, callInfo)
	mock.lockIncWsSubConfirmations.Unlock()
	if mock.IncWsSubConfirmationsFunc == nil {
		return
	}
	mock.IncWsSubConfirmationsFunc()
}

// IncWsSubConfirmationsCalls gets all the calls that were made to IncWsSubConfirmations.
// Check the length with:
//
//	len(mockedSubKeeperMetrics.IncWsSubConfirmationsCalls())
func (mock *SubKeeperMetricsMock) IncWsSubConfirmationsCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockIncWsSubConfirmations.RLock()
	calls = mock.calls.IncWsSubConfirmations
	mock.lockIncWsSubConfirmations.RUnlock()
	return calls
}

// IncWsSubs calls IncWsSubsFunc.
func (mock *SubKeeperMetricsMock) IncWsSubs() {
	callInfo := struct {
	}{}
	mock.lockIncWsSubs.Lock()
	mock.calls.IncWsSubs = append(mock.calls.IncWsSubs, callInfo)
	mock.lockIncWsSubs.Unlock()
	if mock.IncWsSubsFunc == nil {
		return
	}
	mock.IncWsSubsFunc()
}

// IncWsSubsCalls gets all the calls that were made to IncWsSubs.
// Check the length with:
//
//	len(mockedSubKeeperMetrics.IncWsSubsCalls())
func (mock *SubKeeperMetricsMock) IncWsSubsCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockIncWsSubs.RLock()
	calls = mock.calls.IncWsSubs
	mock.lockIncWsSubs.RUnlock()
	return calls
}

// IncWsUnsubConfirmations calls IncWsUnsubConfirmationsFunc.
func (mock *SubKeeperMetricsMock) IncWsUnsubConfirmations() {
	callInfo := struct {
	}{}
	mock.lockIncWsUnsubConfirmations.Lock()
	mock.calls.IncWsUnsubConfirmations = append(mock.calls.IncWsUnsubConfirmations, callInfo)
	mock.lockIncWsUnsubConfirmations.Unlock()
	if mock.IncWsUnsubConfirmationsFunc == nil {
		return
	}
	mock.IncWsUnsubConfirmationsFunc()
}

// IncWsUnsubConfirmationsCalls gets all the calls that were made to IncWsUnsubConfirmations.
// Check the length with:
//
//	len(mockedSubKeeperMetrics.IncWsUnsubConfirmationsCalls())
func (mock *SubKeeperMetricsMock) IncWsUnsubConfirmationsCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockIncWsUnsubConfirmations.RLock()
	calls = mock.calls.IncWsUnsubConfirmations
	mock.lockIncWsUnsubConfirmations.RUnlock()
	return calls
}
