// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package wsreconn

import (
	"sync"
)

// Ensure, that ClientMetricsMock does implement ClientMetrics.
// If this is not the case, regenerate this file with moq.
var _ ClientMetrics = &ClientMetricsMock{}

// ClientMetricsMock is a mock implementation of ClientMetrics.
//
//	func TestSomethingThatUsesClientMetrics(t *testing.T) {
//
//		// make and configure a mocked ClientMetrics
//		mockedClientMetrics := &ClientMetricsMock{
//			IncWsConnectionAttemptsFunc: func()  {
//				panic("mock out the IncWsConnectionAttempts method")
//			},
//			IncWsWritesFunc: func()  {
//				panic("mock out the IncWsWrites method")
//			},
//			SetWsConnClosedFunc: func()  {
//				panic("mock out the SetWsConnClosed method")
//			},
//			SetWsConnOpenFunc: func()  {
//				panic("mock out the SetWsConnOpen method")
//			},
//		}
//
//		// use mockedClientMetrics in code that requires ClientMetrics
//		// and then make assertions.
//
//	}
type ClientMetricsMock struct {
	// IncWsConnectionAttemptsFunc mocks the IncWsConnectionAttempts method.
	IncWsConnectionAttemptsFunc func()

	// IncWsWritesFunc mocks the IncWsWrites method.
	IncWsWritesFunc func()

	// SetWsConnClosedFunc mocks the SetWsConnClosed method.
	SetWsConnClosedFunc func()

	// SetWsConnOpenFunc mocks the SetWsConnOpen method.
	SetWsConnOpenFunc func()

	// calls tracks calls to the methods.
	calls struct {
		// IncWsConnectionAttempts holds details about calls to the IncWsConnectionAttempts method.
		IncWsConnectionAttempts []struct {
		}
		// IncWsWrites holds details about calls to the IncWsWrites method.
		IncWsWrites []struct {
		}
		// SetWsConnClosed holds details about calls to the SetWsConnClosed method.
		SetWsConnClosed []struct {
		}
		// SetWsConnOpen holds details about calls to the SetWsConnOpen method.
		SetWsConnOpen []struct {
		}
	}
	lockIncWsConnectionAttempts sync.RWMutex
	lockIncWsWrites             sync.RWMutex
	lockSetWsConnClosed         sync.RWMutex
	lockSetWsConnOpen           sync.RWMutex
}

// IncWsConnectionAttempts calls IncWsConnectionAttemptsFunc.
func (mock *ClientMetricsMock) IncWsConnectionAttempts() {
	callInfo := struct {
	}{}
	mock.lockIncWsConnectionAttempts.Lock()
	mock.calls.IncWsConnectionAttempts = append(mock.calls.IncWsConnectionAttempts, callInfo)
	mock.lockIncWsConnectionAttempts.Unlock()
	if mock.IncWsConnectionAttemptsFunc == nil {
		return
	}
	mock.IncWsConnectionAttemptsFunc()
}

// IncWsConnectionAttemptsCalls gets all the calls that were made to IncWsConnectionAttempts.
// Check the length with:
//
//	len(mockedClientMetrics.IncWsConnectionAttemptsCalls())
func (mock *ClientMetricsMock) IncWsConnectionAttemptsCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockIncWsConnectionAttempts.RLock()
	calls = mock.calls.IncWsConnectionAttempts
	mock.lockIncWsConnectionAttempts.RUnlock()
	return calls
}

// IncWsWrites calls IncWsWritesFunc.
func (mock *ClientMetricsMock) IncWsWrites() {
	callInfo := struct {
	}{}
	mock.lockIncWsWrites.Lock()
	mock.calls.IncWsWrites = append(mock.calls.IncWsWrites, callInfo)
	mock.lockIncWsWrites.Unlock()
	if mock.IncWsWritesFunc == nil {
		return
	}
	mock.IncWsWritesFunc()
}

// IncWsWritesCalls gets all the calls that were made to IncWsWrites.
// Check the length with:
//
//	len(mockedClientMetrics.IncWsWritesCalls())
func (mock *ClientMetricsMock) IncWsWritesCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockIncWsWrites.RLock()
	calls = mock.calls.IncWsWrites
	mock.lockIncWsWrites.RUnlock()
	return calls
}

// DecWsOpenConnections calls SetWsConnClosedFunc.
func (mock *ClientMetricsMock) DecWsOpenConnections() {
	callInfo := struct {
	}{}
	mock.lockSetWsConnClosed.Lock()
	mock.calls.SetWsConnClosed = append(mock.calls.SetWsConnClosed, callInfo)
	mock.lockSetWsConnClosed.Unlock()
	if mock.SetWsConnClosedFunc == nil {
		return
	}
	mock.SetWsConnClosedFunc()
}

// SetWsConnClosedCalls gets all the calls that were made to SetWsConnClosed.
// Check the length with:
//
//	len(mockedClientMetrics.SetWsConnClosedCalls())
func (mock *ClientMetricsMock) SetWsConnClosedCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockSetWsConnClosed.RLock()
	calls = mock.calls.SetWsConnClosed
	mock.lockSetWsConnClosed.RUnlock()
	return calls
}

// IncWsOpenConnections calls SetWsConnOpenFunc.
func (mock *ClientMetricsMock) IncWsOpenConnections() {
	callInfo := struct {
	}{}
	mock.lockSetWsConnOpen.Lock()
	mock.calls.SetWsConnOpen = append(mock.calls.SetWsConnOpen, callInfo)
	mock.lockSetWsConnOpen.Unlock()
	if mock.SetWsConnOpenFunc == nil {
		return
	}
	mock.SetWsConnOpenFunc()
}

// SetWsConnOpenCalls gets all the calls that were made to SetWsConnOpen.
// Check the length with:
//
//	len(mockedClientMetrics.SetWsConnOpenCalls())
func (mock *ClientMetricsMock) SetWsConnOpenCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockSetWsConnOpen.RLock()
	calls = mock.calls.SetWsConnOpen
	mock.lockSetWsConnOpen.RUnlock()
	return calls
}
