// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package wsreconn

import (
	"encoding/json"
	"sync"
)

// Ensure, that SubPayloaderMock does implement SubPayloader.
// If this is not the case, regenerate this file with moq.
var _ SubPayloader = &SubPayloaderMock{}

// SubPayloaderMock is a mock implementation of SubPayloader.
//
//	func TestSomethingThatUsesSubPayloader(t *testing.T) {
//
//		// make and configure a mocked SubPayloader
//		mockedSubPayloader := &SubPayloaderMock{
//			PayloadFunc: func() (any, func(json.RawMessage)) {
//				panic("mock out the Payload method")
//			},
//		}
//
//		// use mockedSubPayloader in code that requires SubPayloader
//		// and then make assertions.
//
//	}
type SubPayloaderMock struct {
	// PayloadFunc mocks the Payload method.
	PayloadFunc func() (any, func(json.RawMessage))

	// calls tracks calls to the methods.
	calls struct {
		// Payload holds details about calls to the Payload method.
		Payload []struct {
		}
	}
	lockPayload sync.RWMutex
}

// Payload calls PayloadFunc.
func (mock *SubPayloaderMock) Payload() (any, func(json.RawMessage)) {
	callInfo := struct {
	}{}
	mock.lockPayload.Lock()
	mock.calls.Payload = append(mock.calls.Payload, callInfo)
	mock.lockPayload.Unlock()
	if mock.PayloadFunc == nil {
		var (
			vOut  any
			fnOut func(json.RawMessage)
		)
		return vOut, fnOut
	}
	return mock.PayloadFunc()
}

// PayloadCalls gets all the calls that were made to Payload.
// Check the length with:
//
//	len(mockedSubPayloader.PayloadCalls())
func (mock *SubPayloaderMock) PayloadCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockPayload.RLock()
	calls = mock.calls.Payload
	mock.lockPayload.RUnlock()
	return calls
}
