// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package wsreconn

import (
	"encoding/json"
	"sync"
)

// Ensure, that GroupedSubFormatterMock does implement GroupedSubFormatter.
// If this is not the case, regenerate this file with moq.
var _ GroupedSubFormatter[any] = &GroupedSubFormatterMock[any]{}

// GroupedSubFormatterMock is a mock implementation of GroupedSubFormatter.
//
//	func TestSomethingThatUsesGroupedSubFormatter(t *testing.T) {
//
//		// make and configure a mocked GroupedSubFormatter
//		mockedGroupedSubFormatter := &GroupedSubFormatterMock{
//			ConfirmSubFunc: func(topic string, keys []K, data json.RawMessage) bool {
//				panic("mock out the ConfirmSub method")
//			},
//			ConfirmUnsubFunc: func(topic string, keys []K, data json.RawMessage) bool {
//				panic("mock out the ConfirmUnsub method")
//			},
//			SubMessageFunc: func(topic string, keys []K) any {
//				panic("mock out the SubMessage method")
//			},
//			UnsubMessageFunc: func(topic string, keys []K) any {
//				panic("mock out the UnsubMessage method")
//			},
//		}
//
//		// use mockedGroupedSubFormatter in code that requires GroupedSubFormatter
//		// and then make assertions.
//
//	}
type GroupedSubFormatterMock[K comparable] struct {
	// ConfirmSubFunc mocks the ConfirmSub method.
	ConfirmSubFunc func(topic string, keys []K, data json.RawMessage) bool

	// ConfirmUnsubFunc mocks the ConfirmUnsub method.
	ConfirmUnsubFunc func(topic string, keys []K, data json.RawMessage) bool

	// SubMessageFunc mocks the SubMessage method.
	SubMessageFunc func(topic string, keys []K) any

	// UnsubMessageFunc mocks the UnsubMessage method.
	UnsubMessageFunc func(topic string, keys []K) any

	// calls tracks calls to the methods.
	calls struct {
		// ConfirmSub holds details about calls to the ConfirmSub method.
		ConfirmSub []struct {
			// Topic is the topic argument value.
			Topic string
			// Keys is the keys argument value.
			Keys []K
			// Data is the data argument value.
			Data json.RawMessage
		}
		// ConfirmUnsub holds details about calls to the ConfirmUnsub method.
		ConfirmUnsub []struct {
			// Topic is the topic argument value.
			Topic string
			// Keys is the keys argument value.
			Keys []K
			// Data is the data argument value.
			Data json.RawMessage
		}
		// SubMessage holds details about calls to the SubMessage method.
		SubMessage []struct {
			// Topic is the topic argument value.
			Topic string
			// Keys is the keys argument value.
			Keys []K
		}
		// UnsubMessage holds details about calls to the UnsubMessage method.
		UnsubMessage []struct {
			// Topic is the topic argument value.
			Topic string
			// Keys is the keys argument value.
			Keys []K
		}
	}
	lockConfirmSub   sync.RWMutex
	lockConfirmUnsub sync.RWMutex
	lockSubMessage   sync.RWMutex
	lockUnsubMessage sync.RWMutex
}

// ConfirmSub calls ConfirmSubFunc.
func (mock *GroupedSubFormatterMock[K]) ConfirmSub(topic string, keys []K, data json.RawMessage) bool {
	callInfo := struct {
		Topic string
		Keys  []K
		Data  json.RawMessage
	}{
		Topic: topic,
		Keys:  keys,
		Data:  data,
	}
	mock.lockConfirmSub.Lock()
	mock.calls.ConfirmSub = append(mock.calls.ConfirmSub, callInfo)
	mock.lockConfirmSub.Unlock()
	if mock.ConfirmSubFunc == nil {
		var (
			bOut bool
		)
		return bOut
	}
	return mock.ConfirmSubFunc(topic, keys, data)
}

// ConfirmSubCalls gets all the calls that were made to ConfirmSub.
// Check the length with:
//
//	len(mockedGroupedSubFormatter.ConfirmSubCalls())
func (mock *GroupedSubFormatterMock[K]) ConfirmSubCalls() []struct {
	Topic string
	Keys  []K
	Data  json.RawMessage
} {
	var calls []struct {
		Topic string
		Keys  []K
		Data  json.RawMessage
	}
	mock.lockConfirmSub.RLock()
	calls = mock.calls.ConfirmSub
	mock.lockConfirmSub.RUnlock()
	return calls
}

// ConfirmUnsub calls ConfirmUnsubFunc.
func (mock *GroupedSubFormatterMock[K]) ConfirmUnsub(topic string, keys []K, data json.RawMessage) bool {
	callInfo := struct {
		Topic string
		Keys  []K
		Data  json.RawMessage
	}{
		Topic: topic,
		Keys:  keys,
		Data:  data,
	}
	mock.lockConfirmUnsub.Lock()
	mock.calls.ConfirmUnsub = append(mock.calls.ConfirmUnsub, callInfo)
	mock.lockConfirmUnsub.Unlock()
	if mock.ConfirmUnsubFunc == nil {
		var (
			bOut bool
		)
		return bOut
	}
	return mock.ConfirmUnsubFunc(topic, keys, data)
}

// ConfirmUnsubCalls gets all the calls that were made to ConfirmUnsub.
// Check the length with:
//
//	len(mockedGroupedSubFormatter.ConfirmUnsubCalls())
func (mock *GroupedSubFormatterMock[K]) ConfirmUnsubCalls() []struct {
	Topic string
	Keys  []K
	Data  json.RawMessage
} {
	var calls []struct {
		Topic string
		Keys  []K
		Data  json.RawMessage
	}
	mock.lockConfirmUnsub.RLock()
	calls = mock.calls.ConfirmUnsub
	mock.lockConfirmUnsub.RUnlock()
	return calls
}

// SubMessage calls SubMessageFunc.
func (mock *GroupedSubFormatterMock[K]) SubMessage(topic string, keys []K) any {
	callInfo := struct {
		Topic string
		Keys  []K
	}{
		Topic: topic,
		Keys:  keys,
	}
	mock.lockSubMessage.Lock()
	mock.calls.SubMessage = append(mock.calls.SubMessage, callInfo)
	mock.lockSubMessage.Unlock()
	if mock.SubMessageFunc == nil {
		var (
			vOut any
		)
		return vOut
	}
	return mock.SubMessageFunc(topic, keys)
}

// SubMessageCalls gets all the calls that were made to SubMessage.
// Check the length with:
//
//	len(mockedGroupedSubFormatter.SubMessageCalls())
func (mock *GroupedSubFormatterMock[K]) SubMessageCalls() []struct {
	Topic string
	Keys  []K
} {
	var calls []struct {
		Topic string
		Keys  []K
	}
	mock.lockSubMessage.RLock()
	calls = mock.calls.SubMessage
	mock.lockSubMessage.RUnlock()
	return calls
}

// UnsubMessage calls UnsubMessageFunc.
func (mock *GroupedSubFormatterMock[K]) UnsubMessage(topic string, keys []K) any {
	callInfo := struct {
		Topic string
		Keys  []K
	}{
		Topic: topic,
		Keys:  keys,
	}
	mock.lockUnsubMessage.Lock()
	mock.calls.UnsubMessage = append(mock.calls.UnsubMessage, callInfo)
	mock.lockUnsubMessage.Unlock()
	if mock.UnsubMessageFunc == nil {
		var (
			vOut any
		)
		return vOut
	}
	return mock.UnsubMessageFunc(topic, keys)
}

// UnsubMessageCalls gets all the calls that were made to UnsubMessage.
// Check the length with:
//
//	len(mockedGroupedSubFormatter.UnsubMessageCalls())
func (mock *GroupedSubFormatterMock[K]) UnsubMessageCalls() []struct {
	Topic string
	Keys  []K
} {
	var calls []struct {
		Topic string
		Keys  []K
	}
	mock.lockUnsubMessage.RLock()
	calls = mock.calls.UnsubMessage
	mock.lockUnsubMessage.RUnlock()
	return calls
}
