// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package wsreconn

import (
	"encoding/json"
	"sync"
)

// Ensure, that SoloSubFormatterMock does implement SoloSubFormatter.
// If this is not the case, regenerate this file with moq.
var _ SoloSubFormatter = &SoloSubFormatterMock{}

// SoloSubFormatterMock is a mock implementation of SoloSubFormatter.
//
//	func TestSomethingThatUsesSoloSubFormatter(t *testing.T) {
//
//		// make and configure a mocked SoloSubFormatter
//		mockedSoloSubFormatter := &SoloSubFormatterMock{
//			ConfirmSubFunc: func(topic string, data json.RawMessage) bool {
//				panic("mock out the ConfirmSub method")
//			},
//			ConfirmUnsubFunc: func(topic string, data json.RawMessage) bool {
//				panic("mock out the ConfirmUnsub method")
//			},
//			SubMessageFunc: func(topic string) any {
//				panic("mock out the SubMessage method")
//			},
//			UnsubMessageFunc: func(topic string) any {
//				panic("mock out the UnsubMessage method")
//			},
//		}
//
//		// use mockedSoloSubFormatter in code that requires SoloSubFormatter
//		// and then make assertions.
//
//	}
type SoloSubFormatterMock struct {
	// ConfirmSubFunc mocks the ConfirmSub method.
	ConfirmSubFunc func(topic string, data json.RawMessage) bool

	// ConfirmUnsubFunc mocks the ConfirmUnsub method.
	ConfirmUnsubFunc func(topic string, data json.RawMessage) bool

	// SubMessageFunc mocks the SubMessage method.
	SubMessageFunc func(topic string) any

	// UnsubMessageFunc mocks the UnsubMessage method.
	UnsubMessageFunc func(topic string) any

	// calls tracks calls to the methods.
	calls struct {
		// ConfirmSub holds details about calls to the ConfirmSub method.
		ConfirmSub []struct {
			// Topic is the topic argument value.
			Topic string
			// Data is the data argument value.
			Data json.RawMessage
		}
		// ConfirmUnsub holds details about calls to the ConfirmUnsub method.
		ConfirmUnsub []struct {
			// Topic is the topic argument value.
			Topic string
			// Data is the data argument value.
			Data json.RawMessage
		}
		// SubMessage holds details about calls to the SubMessage method.
		SubMessage []struct {
			// Topic is the topic argument value.
			Topic string
		}
		// UnsubMessage holds details about calls to the UnsubMessage method.
		UnsubMessage []struct {
			// Topic is the topic argument value.
			Topic string
		}
	}
	lockConfirmSub   sync.RWMutex
	lockConfirmUnsub sync.RWMutex
	lockSubMessage   sync.RWMutex
	lockUnsubMessage sync.RWMutex
}

// ConfirmSub calls ConfirmSubFunc.
func (mock *SoloSubFormatterMock) ConfirmSub(topic string, data json.RawMessage) bool {
	callInfo := struct {
		Topic string
		Data  json.RawMessage
	}{
		Topic: topic,
		Data:  data,
	}
	mock.lockConfirmSub.Lock()
	mock.calls.ConfirmSub = append(mock.calls.ConfirmSub, callInfo)
	mock.lockConfirmSub.Unlock()
	if mock.ConfirmSubFunc == nil {
		var (
			bOut bool
		)
		return bOut
	}
	return mock.ConfirmSubFunc(topic, data)
}

// ConfirmSubCalls gets all the calls that were made to ConfirmSub.
// Check the length with:
//
//	len(mockedSoloSubFormatter.ConfirmSubCalls())
func (mock *SoloSubFormatterMock) ConfirmSubCalls() []struct {
	Topic string
	Data  json.RawMessage
} {
	var calls []struct {
		Topic string
		Data  json.RawMessage
	}
	mock.lockConfirmSub.RLock()
	calls = mock.calls.ConfirmSub
	mock.lockConfirmSub.RUnlock()
	return calls
}

// ConfirmUnsub calls ConfirmUnsubFunc.
func (mock *SoloSubFormatterMock) ConfirmUnsub(topic string, data json.RawMessage) bool {
	callInfo := struct {
		Topic string
		Data  json.RawMessage
	}{
		Topic: topic,
		Data:  data,
	}
	mock.lockConfirmUnsub.Lock()
	mock.calls.ConfirmUnsub = append(mock.calls.ConfirmUnsub, callInfo)
	mock.lockConfirmUnsub.Unlock()
	if mock.ConfirmUnsubFunc == nil {
		var (
			bOut bool
		)
		return bOut
	}
	return mock.ConfirmUnsubFunc(topic, data)
}

// ConfirmUnsubCalls gets all the calls that were made to ConfirmUnsub.
// Check the length with:
//
//	len(mockedSoloSubFormatter.ConfirmUnsubCalls())
func (mock *SoloSubFormatterMock) ConfirmUnsubCalls() []struct {
	Topic string
	Data  json.RawMessage
} {
	var calls []struct {
		Topic string
		Data  json.RawMessage
	}
	mock.lockConfirmUnsub.RLock()
	calls = mock.calls.ConfirmUnsub
	mock.lockConfirmUnsub.RUnlock()
	return calls
}

// SubMessage calls SubMessageFunc.
func (mock *SoloSubFormatterMock) SubMessage(topic string) any {
	callInfo := struct {
		Topic string
	}{
		Topic: topic,
	}
	mock.lockSubMessage.Lock()
	mock.calls.SubMessage = append(mock.calls.SubMessage, callInfo)
	mock.lockSubMessage.Unlock()
	if mock.SubMessageFunc == nil {
		var (
			vOut any
		)
		return vOut
	}
	return mock.SubMessageFunc(topic)
}

// SubMessageCalls gets all the calls that were made to SubMessage.
// Check the length with:
//
//	len(mockedSoloSubFormatter.SubMessageCalls())
func (mock *SoloSubFormatterMock) SubMessageCalls() []struct {
	Topic string
} {
	var calls []struct {
		Topic string
	}
	mock.lockSubMessage.RLock()
	calls = mock.calls.SubMessage
	mock.lockSubMessage.RUnlock()
	return calls
}

// UnsubMessage calls UnsubMessageFunc.
func (mock *SoloSubFormatterMock) UnsubMessage(topic string) any {
	callInfo := struct {
		Topic string
	}{
		Topic: topic,
	}
	mock.lockUnsubMessage.Lock()
	mock.calls.UnsubMessage = append(mock.calls.UnsubMessage, callInfo)
	mock.lockUnsubMessage.Unlock()
	if mock.UnsubMessageFunc == nil {
		var (
			vOut any
		)
		return vOut
	}
	return mock.UnsubMessageFunc(topic)
}

// UnsubMessageCalls gets all the calls that were made to UnsubMessage.
// Check the length with:
//
//	len(mockedSoloSubFormatter.UnsubMessageCalls())
func (mock *SoloSubFormatterMock) UnsubMessageCalls() []struct {
	Topic string
} {
	var calls []struct {
		Topic string
	}
	mock.lockUnsubMessage.RLock()
	calls = mock.calls.UnsubMessage
	mock.lockUnsubMessage.RUnlock()
	return calls
}
