// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package wsclient

import (
	"sync"
)

// Ensure, that MetricsMock does implement Metrics.
// If this is not the case, regenerate this file with moq.
var _ Metrics = &MetricsMock{}

// MetricsMock is a mock implementation of Metrics.
//
//	func TestSomethingThatUsesMetrics(t *testing.T) {
//
//		// make and configure a mocked Metrics
//		mockedMetrics := &MetricsMock{
//			DecWsOpenConnectionsFunc: func()  {
//				panic("mock out the DecWsOpenConnections method")
//			},
//			IncWsOpenConnectionsFunc: func()  {
//				panic("mock out the IncWsOpenConnections method")
//			},
//		}
//
//		// use mockedMetrics in code that requires Metrics
//		// and then make assertions.
//
//	}
type MetricsMock struct {
	// DecWsOpenConnectionsFunc mocks the DecWsOpenConnections method.
	DecWsOpenConnectionsFunc func()

	// IncWsOpenConnectionsFunc mocks the IncWsOpenConnections method.
	IncWsOpenConnectionsFunc func()

	// calls tracks calls to the methods.
	calls struct {
		// DecWsOpenConnections holds details about calls to the DecWsOpenConnections method.
		DecWsOpenConnections []struct {
		}
		// IncWsOpenConnections holds details about calls to the IncWsOpenConnections method.
		IncWsOpenConnections []struct {
		}
	}
	lockDecWsOpenConnections sync.RWMutex
	lockIncWsOpenConnections sync.RWMutex
}

// DecWsOpenConnections calls DecWsOpenConnectionsFunc.
func (mock *MetricsMock) DecWsOpenConnections() {
	callInfo := struct {
	}{}
	mock.lockDecWsOpenConnections.Lock()
	mock.calls.DecWsOpenConnections = append(mock.calls.DecWsOpenConnections, callInfo)
	mock.lockDecWsOpenConnections.Unlock()
	if mock.DecWsOpenConnectionsFunc == nil {
		return
	}
	mock.DecWsOpenConnectionsFunc()
}

// DecWsOpenConnectionsCalls gets all the calls that were made to DecWsOpenConnections.
// Check the length with:
//
//	len(mockedMetrics.DecWsOpenConnectionsCalls())
func (mock *MetricsMock) DecWsOpenConnectionsCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockDecWsOpenConnections.RLock()
	calls = mock.calls.DecWsOpenConnections
	mock.lockDecWsOpenConnections.RUnlock()
	return calls
}

// IncWsOpenConnections calls IncWsOpenConnectionsFunc.
func (mock *MetricsMock) IncWsOpenConnections() {
	callInfo := struct {
	}{}
	mock.lockIncWsOpenConnections.Lock()
	mock.calls.IncWsOpenConnections = append(mock.calls.IncWsOpenConnections, callInfo)
	mock.lockIncWsOpenConnections.Unlock()
	if mock.IncWsOpenConnectionsFunc == nil {
		return
	}
	mock.IncWsOpenConnectionsFunc()
}

// IncWsOpenConnectionsCalls gets all the calls that were made to IncWsOpenConnections.
// Check the length with:
//
//	len(mockedMetrics.IncWsOpenConnectionsCalls())
func (mock *MetricsMock) IncWsOpenConnectionsCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockIncWsOpenConnections.RLock()
	calls = mock.calls.IncWsOpenConnections
	mock.lockIncWsOpenConnections.RUnlock()
	return calls
}
