name: QA
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

defaults:
  run:
    shell: bash

env:
  GOPRIVATE: github.com/jellydator
  DEPS_GITHUB_TOKEN: ${{ secrets.DEPS_GITHUB_TOKEN }}

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v7

      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version-file: go.mod

      - name: Installing dependencies
        run: |
            git config --global url.https://$DEPS_GITHUB_TOKEN@github.com/.insteadOf https://github.com/
            go mod download

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.11

  test:
    name: Unit testing
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v7

      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version-file: go.mod

      - name: Installing dependencies
        run: |
            git config --global url.https://$DEPS_GITHUB_TOKEN@github.com/.insteadOf https://github.com/
            go mod download

      - name: Run unit tests
        run: make test
        env:
          WETSOCKS_TEST_MIN_COV: ${{ vars.MIN_COVERAGE }}
